[libraries]
defaultlib.files = [
  "accelerator/rtl/systolic_pkg.vhd",
  "accelerator/rtl/systolic_pe.vhd",
  "accelerator/rtl/systolic_array.vhd",
  "accelerator/rtl/systolic_controller.vhd",
  "accelerator/rtl/buffer_unit.vhd",
  "accelerator/rtl/queue_buffer.vhd",
  "accelerator/rtl/systolic_engine.vhd",
  "accelerator/sim/tb_buffer_unit.vhd",
  "accelerator/sim/tb_systolic_pe.vhd",
  "accelerator/sim/tb_systolic_controller.vhd",
  "accelerator/sim/tb_systolic_array.vhd",
]
